@identity = https://localhost:5001
@clientCredClientId = m2m.api
@clientCredClientSecret = 511536EF-F270-4058-80CA-1C89C192F69A
@clientCredScope = api1 api2

###
# @name clientCredResponse
POST {{identity}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientCredClientId}}&client_secret={{clientCredClientSecret}}&grant_type=client_credentials&scope={{clientCredScope}}
###
@clientCredToken = {{clientCredResponse.response.body.access_token}}

###
# Get all messages
GET https://localhost:7274/api/messages
Authorization: Bearer {{clientCredToken}}



###
@passwordClientId = password-login
@passwordClientSecret = 84c4d8ef-2fe6-4acc-8cf2-eb15b51fba0d
@passwordScope = api1
@passwordUsername = bob
@passwordPassword = bob
###
# @name passwordResponse
POST {{identity}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{passwordClientId}}&client_secret={{passwordClientSecret}}&grant_type=password&scope={{passwordScope}}&username={{passwordUsername}}&password={{passwordPassword}}
###
@passwordToken = {{passwordResponse.response.body.access_token}}

###
# Get received messages for bob
GET https://localhost:7274/api/messages/2/to
Authorization: Bearer {{passwordToken}}

###
# Get sent messages for bob
GET https://localhost:7274/api/messages/2/from
Authorization: Bearer {{passwordToken}}

###
# Get received messages for alice
GET https://localhost:7274/api/messages/1/to
Authorization: Bearer {{passwordToken}}

###
# Get sent messages for alice
GET https://localhost:7274/api/messages/1/from
Authorization: Bearer {{passwordToken}}
